
export enum SocketEvent {
	START_GAME = "START_GAME",
	SET_SETTINGS = "SET_SETTINGS",
	SET_PLAYERS = "SET_PLAYERS",
	UPDATE_GAME_STATUS = "UPDATE_GAME_STATUS",
	ADD_DART_THROW = "ADD_DART_THROW",
	NEXT_PLAYER = "NEXT_PLAYER",
	UNDO_LAST_DART = "UNDO_LAST_DART",
	SPEAK = "SPEAK",
}
